version: 1.0

backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple

frontend:
  phases:
    preBuild:
      commands:
        - npm ci --prefer-offline # Ensure exact dependencies are installed
    build:
      commands:
        - npm run build
artifacts:
  baseDirectory: build
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*